#!/bin/bash

# if unset we'll expect our input to reside in the directory alongside our script
DIR=$(dirname "$0")
SRCDIR=${SRCDIR:-$DIR/..}
BUILDDIR=${BUILDDIR:-$DIR/..}

zcat < "$SRCDIR/test/testfile.marc.gz" | "$BUILDDIR/marc" -Fxml  > "$BUILDDIR/test/marc-xml.output"
zcat < "$SRCDIR/test/testfile.xml.gz" | diff "$BUILDDIR/test/marc-xml.output" -
