#!/bin/bash

set -euxo pipefail

# if unset we'll expect our input to reside in the directory alongside our script
DIR=$(dirname "$0")
SRCDIR=${SRCDIR:-$DIR}
BUILDDIR=${BUILDDIR:-$DIR}

zcat < "$SRCDIR/testfile.marc.gz" | ./marc print > "$BUILDDIR/marc-print.output"
zcat < "$SRCDIR/marc-print.txt.gz" | diff "$BUILDDIR/marc-print.output" -
