#!/bin/bash

which valgrind >& /dev/null || { echo "can't find valgrind; skippint test..."; exit 77; }

zcat < test/testfile.marc.gz | ./libtool --mode=execute valgrind --leak-check=full --log-file=test/dynamic-alloc.valgrind test/dynamic-alloc -o /dev/null
grep 'ERROR SUMMARY: 0' test/dynamic-alloc.valgrind || { echo "leak detected in dynamic-alloc; exiting..."; exit 1; }
