#!/bin/bash

which valgrind >& /dev/null || { echo "can't find valgrind; skippint test..."; exit 77; }

cmd=$(echo "$0" | cut -d- -s -f2)

[[ -n "$cmd" ]] || { echo "this script wasn't meant to be run without a -command suffix!"; exit 99; }

logfile="test/marc-$cmd.valgrind"
zcat < test/testfile.marc.gz | ./libtool --mode=execute valgrind --leak-check=full --log-file="$logfile" ./marc "$cmd" -o /dev/null
grep 'ERROR SUMMARY: 0' "$logfile" || { echo "leak detected in marc $cmd; exiting..."; exit 1; }
