#!/bin/bash

which valgrind >& /dev/null || { echo "can't find valgrind; skipping test..."; exit 77; }

# if unset we'll expect our input to reside in the directory alongside our script
DIR=$(dirname "$0")
SRCDIR=${SRCDIR:-$DIR}
BUILDDIR=${BUILDDIR:-$DIR}

logfile="$BUILDDIR/dynamic-alloc.valgrind"
zcat < "$SRCDIR/testfile.marc.gz" | ./libtool --mode=execute valgrind --leak-check=full --log-file="$logfile" "$BUILDDIR/dynamic-alloc" -o /dev/null
grep 'ERROR SUMMARY: 0' test/dynamic-alloc.valgrind || { echo "leak detected in dynamic-alloc; exiting..."; exit 1; }
